# Use Nixpacks providers instead of manual nixPkgs
[providers]
node = "24"

[phases.install]
cmds = [
  "cd mystica-express && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd mystica-express && pnpm build"
]

[start]
cmd = "cd mystica-express && pnpm start"
