[build]
builder = "NIXPACKS"
buildCommand = "cd mystica-express && pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "cd mystica-express && pnpm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
