-- Migration: Add image_url column to enemytypes table
-- Purpose: Store R2 URLs for enemy type images generated by scripts
-- Date: 2025-10-25

-- Add image_url column
ALTER TABLE enemytypes
ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Add comment for documentation
COMMENT ON COLUMN enemytypes.image_url IS 'URL to enemy type base image in R2 storage (e.g., https://pub-xxx.r2.dev/monsters/dragon-rubberhose.png)';

-- Verify migration
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'enemytypes'
  AND column_name = 'image_url';
