-- Migration: Add image_url column to materials table
-- Purpose: Store R2 URLs for material images generated by scripts
-- Date: 2025-10-25

-- Add image_url column
ALTER TABLE materials
ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Add comment for documentation
COMMENT ON COLUMN materials.image_url IS 'URL to material image in R2 storage (e.g., https://pub-xxx.r2.dev/materials/wood-rubberhose.png)';

-- Verify migration
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'materials'
  AND column_name = 'image_url';
