# Product Requirements Document
# Keep descriptions brief. Features link to feature-title.yaml specs.

status: draft
last_updated: 2025-10-20

overview:
  project_name: "New Mystica"
  summary: "A location-based mobile RPG where players explore real-world locations to discover enemies, collect items and pets, and engage in tactical combat. Players navigate using maps, craft powerful equipment, and build their collection through location-specific gameplay."
  problem_statement: "Existing location-based games lack deep RPG mechanics and meaningful item progression. Players want exploration-driven gameplay that rewards both movement and strategic decision-making with persistent character growth."

scope:
  in_scope:
    - Location-based enemy and item discovery via map integration
    - Tactical combat system with timing-based mechanics
    - Item and pet collection with styled variants (normal/styled)
    - AI-generated items with stat distributions
    - Native iOS/macOS application
    - Backend API for data persistence and AI generation
  out_of_scope:
    - PvP combat (v1)
    - Social/multiplayer features (v1)
    - Trading system (v1)
    - Android support
    - Web frontend

summary:
  goal: "Create an engaging location-based RPG that combines exploration, collection, and strategic combat to drive daily active play sessions"
  primary_users:
    - "Mobile gamers (18-35) who enjoy RPG progression and collection mechanics"
    - "Location-based game players seeking deeper gameplay than existing titles"
    - "Collectors motivated by rare variants and crafting systems"
  key_problems_solved:
    - Provides meaningful RPG progression in location-based gameplay
    - Rewards both exploration (discovery) and strategy (combat/crafting)
    - Offers deep item customization through AI generation and crafting
    - Creates scarcity and value through location-specific items and styled variants

features:
  - id: "F-01"
    description: "Geolocation & Map System - Google Maps integration for real-world navigation and location-based item/enemy discovery"
    priority: "critical"
    status: "planned"

  - id: "F-02"
    description: "Combat System - Timing-based combat with attack multiplier dial, stat calculations, and turn-based flow"
    priority: "critical"
    status: "planned"

  - id: "F-03"
    description: "Base Items & Equipment System - 8 equipment slots (weapon, offhand, head, armor, feet, accessory_1, accessory_2, pet) with normalized stat blocks and level progression"
    priority: "critical"
    status: "planned"

  - id: "F-04"
    description: "Materials System - Collectible materials that modify item stats (max 3 per item, hard limit), with normal and styled variants, removable for gold (100 × item level). Global image cache with craft count tracking."
    priority: "critical"
    status: "planned"

  - id: "F-05"
    description: "Material Drop System - Enemies drop gold (always) and materials (60% chance), with 5% styled rate and level-scaled rewards"
    priority: "critical"
    status: "planned"

  - id: "F-06"
    description: "Item Upgrade System - Spend gold to level up items, increasing stat values while maintaining normalized ratios"
    priority: "high"
    status: "planned"

  - id: "F-07"
    description: "User Authentication - Secure registration, login, and persistent user profiles"
    priority: "critical"
    status: "planned"

  - id: "F-08"
    description: "Design System - Consistent UI components (buttons, typography, colors) across all screens"
    priority: "high"
    status: "planned"

  - id: "F-09"
    description: "Inventory Management - View, filter, and sort all owned items; equip/unequip items to 8 equipment slots; save up to 5 loadout configurations for quick switching (post-MVP)"
    priority: "high"
    status: "planned"

  - id: "F-10"
    description: "Premium Items & Monetization - Multi-currency system (GOLD active, GEMS reserved for future IAP); premium item catalog and special content (placeholder spec - IAP not yet implemented)"
    priority: "medium"
    status: "planned"

  - id: "F-11"
    description: "Pet Personality System - AI-powered dynamic pet personalities that generate contextual trash-talk and commentary during combat based on pet traits and battle events"
    priority: "high"
    status: "planned"

  - id: "F-12"
    description: "Enemy AI Personality System - AI-powered enemy personalities that generate contextual trash-talk during combat based on enemy type, game state, and player history (attempts, win/loss record, streaks)"
    priority: "high"
    status: "planned"

  - id: "F-13"
    description: "Progression Balance & Endgame Content - Long-term progression with soft level caps, prestige/rebirth system, additional gold sinks, and endgame achievement goals"
    priority: "medium"
    status: "planned"

core_systems:
  economy:
    currencies:
      - code: GOLD
        status: active
        description: "Primary currency earned from combat, quests, achievements"
        sources: "Combat victories (avg 50 gold), daily quests (200 gold), achievements (500-2000 gold)"
        sinks: "Item upgrades (100-5000 gold), material replacement (50-1250 gold), cosmetic features (250-5000 gold)"

      - code: GEMS
        status: reserved
        description: "Premium currency reserved for future in-app purchases"
        sources: "IAP (not yet implemented)"
        sinks: "Premium items, cosmetics, convenience features (not yet implemented)"

    ledger:
      table: EconomyTransactions
      description: "All currency changes audited for inflation tracking and abuse detection"
      track: "Every gold/gem change with source, amount, balance snapshot"

  progression:
    player_levels:
      table: PlayerProgression
      description: "Account-level XP and level system separate from item levels"
      xp_sources: "Combat, quests, achievements, milestones"
      soft_cap: "Level 50 - exponential scaling beyond (1.5x multiplier per level)"
      max_level: "100 (theoretical, near-impossible)"

    prestige:
      status: post-MVP
      description: "Reset level to 1, keep items, earn permanent gold bonus"
      requirement: "Level 50+"
      max_prestige: 10
      bonus: "5% permanent gold bonus per prestige rank"

    vanity_level:
      description: "Sum of all equipped item levels (cached, trigger-maintained)"
      purpose: "Visual progression indicator, achievement milestones"

  notifications:
    push:
      table: DeviceTokens
      platforms: ["iOS", "Android", "web"]
      triggers: "Styled material collected, daily quest available, friend activity"

    in_game:
      types: "Level up, achievement unlocked, combat victory, material drop"

  analytics:
    tutorial_funnel:
      events: ["tutorial_started", "tutorial_completed", "first_combat", "first_upgrade", "first_craft"]
      purpose: "Measure onboarding conversion and identify drop-off points"

    progression_tracking:
      events: ["xp_gained", "level_up", "prestige_activated"]
      purpose: "Monitor player advancement and engagement"

    economy_monitoring:
      events: ["currency_balance_changed", "item_upgraded", "material_replaced"]
      purpose: "Track gold flow, inflation, and spending patterns"

technical_constraints:
  platforms:
    - iOS 17+
    - macOS 14+ (secondary)
  backend:
    - Express.js 4.16.x
    - Supabase PostgreSQL for persistence
    - AI service for item generation
    - Google Maps API integration
  frontend:
    - SwiftUI for native UI
    - SwiftData for local caching
    - CoreLocation for geolocation
  deployment:
    - Railway for backend hosting
    - TestFlight for mobile distribution
  performance:
    - Map rendering must support smooth scrolling with 100+ location markers
    - Combat animations must run at 60fps
    - Item generation API response time < 2s

timeline:
  milestones:
    - phase: "Light MVP (3 days)"
      target: "2025-10-22"
      deliverables:
        - Basic map view with static locations
        - Simple combat prototype (dial mechanic)
        - Item data model with mock data
        - Basic UI design system

    - phase: "Full MVP (2 weeks)"
      target: "2025-11-05"
      deliverables:
        - Google Maps integration with real geolocation
        - Complete combat system with stats calculation
        - Items and pets system with equipping
        - AI item generation backend
        - Basic material application system
        - User authentication and profiles

    - phase: "Finished Product (2 months)"
      target: "2026-01-05"
      deliverables:
        - Full material application system
        - Style variants and rarity system
        - Premium items with single-location spawns
        - Polished UI/UX across all screens
        - Performance optimization
        - App Store submission
        - Analytics and monitoring

success_metrics:
  - metric: "Daily Active Users (DAU)"
    target: "1,000 DAU within first month post-launch"
  - metric: "Session Length"
    target: "Average 15+ minutes per session"
  - metric: "Retention (Day 7)"
    target: "40% D7 retention"
  - metric: "Material Application Rate"
    target: "70% of collected materials applied to items within 24 hours"
  - metric: "Location Visits"
    target: "Average 3+ unique locations visited per session"
  - metric: "Upgrade Engagement"
    target: "Average 2+ item upgrades per active user per day"

  - metric: "Currency Inflation Rate"
    target: "Gold supply growth < 10% per month (economy balance)"

  - metric: "Tutorial Completion Rate"
    target: "60%+ of registered users complete tutorial"

  - metric: "First Combat Conversion"
    target: "80%+ of tutorial completers engage in first combat within 5 minutes"

  - metric: "Loadout Usage"
    target: "40%+ of level 20+ players create at least one loadout"

  - metric: "Prestige Adoption"
    target: "20%+ of level 50+ players prestige at least once"

notes: |
  Core gameplay loop:
  1. Navigate to real-world location using map
  2. Discover location-specific enemy with level = player average item level
  3. Engage in timing-based combat (attack dial + defense dial)
  4. Defeat enemy → receive gold + material drops (60% chance, 5% styled)
  5. Apply materials to base items (max 3 materials per item)
  6. Upgrade items with gold to increase level and stats
  7. Equip stronger items and repeat with harder enemies

  Key differentiators:
  - Tactical combat with skill-based timing (attack AND defense dials)
  - Material-based customization (stack up to 3 materials per item)
  - Normalized stat system (stats sum to 1.0, materials modify by ±0.1-0.3)
  - Dynamic enemy scaling (always appropriately challenging)
  - Styled materials (visual variants) for collection variety
  - Vanity level progression system (driven by item levels)

  Material System Details:
  - Base items have normalized stats: {atkPower, atkAccuracy, defPower, defAccuracy} sum to 1.0
  - Materials apply modifiers like +0.2 atkPower, -0.1 defSpeed (must sum to 0)
  - Max 3 materials per item (hard limit, absolute maximum)
  - Materials can be removed for gold (100 × item level), returns to stack
  - To replace: remove old material + apply new material (two operations)
  - Styled materials: visual variants with normal stat effectiveness
  - Image generation: 20s sync for MVP, async with crafting times in later MVP
  - Global ItemImageCache stores combo images with craft_count tracking
  - Material Rarity: Auto-classified into strength tiers (common/uncommon/rare/epic) based on stat modifier magnitude (not a stored property)
  - Drop Frequency: Tier-based system controls how often materials drop per location using tier multipliers (common=1.0, epic=0.15)
  - Level Gating: Inappropriate materials (e.g., Hello Kitty) excluded from early-level pools, unlocked at higher levels

  Combat Mechanics:
  - Attack dial: Timing determines damage multiplier (atkAccuracy = hit window size)
  - Defense dial: Timing determines damage reduction % (defAccuracy = block window size)
  - atkPower scales base damage, defPower scales reduction percentage
  - Enemy stats scale to player's average equipped item level

  Progression Systems:
  - Item levels: Spend gold to level up items (stats scale proportionally)
  - Vanity level: Sum of all equipped item levels (8 slots), cached and trigger-maintained
  - Player level: Separate XP-based progression tracked in PlayerProgression table
  - Enemy difficulty: Scales dynamically to player's average item level

  Economy & Progression Details:
  - Multi-currency system: GOLD (active), GEMS (reserved for IAP)
  - All currency changes tracked via EconomyTransactions ledger
  - Player progression separate from item levels (PlayerProgression table)
  - XP formula: Linear to level 50, exponential beyond (soft cap)
  - Prestige system (post-MVP): Reset to level 1, keep items, +5% gold bonus per rank
  - Gold sinks: Item upgrades, material replacement, cosmetics, loadout expansion, fast travel
  - Economy balance: ~1000-2000 gold/day income, major sinks 1000-5000 gold

  Inventory & Equipment:
  - 8 equipment slots: weapon, offhand, head, armor, feet, accessory_1, accessory_2, pet
  - Loadout system (post-MVP): Save up to 5 equipment configurations
  - Quick loadout switching for different playstyles (combat, farming, exploration)
  - Inventory filtering by slot type, sorting by level/rarity/date
  - No inventory size limit in MVP (soft cap post-MVP)

  Endgame Content (Post-MVP):
  - Combat Mastery: Defeat each enemy type 100 times
  - Collection Completion: Obtain all 26 item types and all style variants
  - Vanity Milestone: Reach vanity level 500
  - Gold Hoarder: Accumulate 100,000 gold
  - Prestige Ranks: Reach prestige level 5-10
  - Seasonal leaderboards and challenges
